Upgrade snowflake-sdk patch version
deliverr/data-knex-snowflake-dialect pull request #72
Opened 2024-09-26 19:18 UTC by mbradydeliverr

2024-09-26 19:42 UTC, mbradydeliverr commented on .circleci/config.yml
> -    - image: circleci/node:12
Update the image. Circleci images are deprecated and may be removed - cimg/node is the preferred registry

2024-09-26 19:43 UTC, mbradydeliverr commented on .circleci/config.yml
> -          context:
wrong context - we need `npm-publish` to be able to WRITE

2024-09-26 19:43 UTC, mbradydeliverr commented on .circleci/config.yml
> -              only: master
we want to publish from this branch (0.x) which is for 0.X.X knex versions

2024-09-26 19:44 UTC, mbradydeliverr commented on package.json
> -    "snowflake-sdk": "1.6.0"
Grab all the latest and greatest bugfixes and use ~ to allow us to pick up any new bug fixes

2024-09-26 19:53 UTC, mbradydeliverr commented on package.json
> +    "mkdirp": "^0.5.6",
old mkdirp as a vulnerability which was flagged by wiz, this explicitly targets a version with a fix

2024-09-26 19:54 UTC, mbradydeliverr commented on package.json
> +    "snowflake-sdk": "~1.6.23"
Grab the latest 1.6.X version with vuln+bug fix patches

2024-09-26 19:54 UTC, mbradydeliverr commented on .circleci/config.yml
> +    - image: cimg/node:12.22.12
Update the image. Circleci images are deprecated and may be removed - cimg/node is the preferred registry

2024-09-26 20:34 UTC, mbradydeliverr commented on package.json
> +    "mkdirp": "^0.5.6",
Specifically, it was an old minimist package

2024-09-27 12:56 UTC, couimet commented on .circleci/config.yml
> +    - image: cimg/node:12.22.12
Could we take this opportunity and move to `Node.js v20` ?

I understand it's beyond only focusing on the `VULN` ticket, but I'm curious to know if you've considered it given you've already updated a few repo to `v20` over the last few weeks.

2024-09-27 13:03 UTC, couimet commented on package.json
> +    "snowflake-sdk": "~1.6.23"
The latest `1.6.x` version goes back to ~1 year ago.

I couldn't find a `CHANGELOG` on https://www.npmjs.com/package/snowflake-sdk, but is there a reason not to go with the latest-available version ?

2024-09-27 13:04 UTC, couimet reviewed
Added a few standalone questions

2024-09-27 13:09 UTC, couimet requested changes
Aren't we missing a version change on `package.json` so our other services can get access to the _latest & greatest_ package with the `VULN` fix ?

Also: I noticed this PR targets branch `0.x`. https://github.com/search?q=org%3Adeliverr+knex-snowflake-dialect+language%3AJSON&type=code&l=JSON shows some of our projects have a dependency on version `1.x.y` of the current package. I guess you'll work on a 2nd PR that targets `master` branch with similar changes ?

2024-09-27 14:05 UTC, mbradydeliverr commented
> Aren't we missing a version change on `package.json` so our other services can get access to the _latest & greatest_ package with the `VULN` fix ?
> 
> Also: I noticed this PR targets branch `0.x`. https://github.com/search?q=org%3Adeliverr+knex-snowflake-dialect+language%3AJSON&type=code&l=JSON shows some of our projects have a dependency on version `1.x.y` of the current package. I guess you'll work on a 2nd PR that targets `master` branch with similar changes ?

The circleci pipeline will bump the version automatically but ya good call on doing this for master as well. I just didn't think about that

2024-09-27 14:05 UTC, mbradydeliverr commented on package.json
> +    "snowflake-sdk": "~1.6.23"
I'm scared of breaking things since I'm not an expert here. I was thinking patch version upgrade was safer

2024-09-27 14:11 UTC, mbradydeliverr commented on package.json
> +    "snowflake-sdk": "~1.6.23"
@couimet We _could_ go up to 1.8.X I think without messing around too much in this PR. I really really don't want to do too much here. I'll create a jira ticket to capture the other changes this repo should get after I deal with the vulnerability 


Reference:
https://docs.snowflake.com/en/release-notes/clients-drivers/nodejs-2023#bcr-behavior-change-release-change:~:text=BCR%20(Behavior%20Change%20Release)%20Change

This drops support for node 12 which this repo is still technically using to build it.

2024-09-27 14:11 UTC, mbradydeliverr commented on .circleci/config.yml
> +    - image: cimg/node:12.22.12
@couimet Ah, I mentioned in the other ticket - We _could_, I'd like to try to do that after though

2024-09-27 14:25 UTC, couimet commented on package.json
> +    "snowflake-sdk": "~1.8.0"
@mbradydeliverr I wish we could add comments to the `package.json` files... 😞 

For visibility-sake (given this is a public repo), can you please add more details here about why we stopped at `1.8.0` instead of going for `1.9.x` ?

2024-09-27 14:27 UTC, couimet approved these changes
LGTM ! Thanks for looking into this ! Looking forward to see similar improvements targeting `master` branch.

2024-09-27 14:27 UTC, mbradydeliverr commented on package.json
> +    "snowflake-sdk": "~1.8.0"
It looks like upgrading to 1.8.0 is safe after reading [the release notes](https://docs.snowflake.com/en/release-notes/clients-drivers/nodejs-2023#:~:text=BCR%20(Behavior%20Change%20Release)%20Change)

1.9.0 introduces a behaviour change which drops support for node 12 which this repo is still using. 

We will upgrade the dependency and node in a follow-up.

2024-09-27 14:30 UTC, mbradydeliverr commented
> > LGTM ! Thanks for looking into this ! Looking forward to see similar improvements targeting `master` branch.
> 
> @couimet #73 👀

@couimet Oops, hold up. I gotta fix the circleci config there as well

2024-09-27 14:33 UTC, merged

2024-09-27 16:26 UTC, couimet commented on .circleci/config.yml
> +              only: master,0.x
@mbradydeliverr Post-approval, I noticed this notation is different from the one we used in https://github.com/deliverr/data-knex-snowflake-dialect/blob/fa93d7d6c98950927f1d1cb5a79e0b3c411b83d2/.circleci/config.yml#L86-L88

Will this be a problem ?

Looking at https://app.circleci.com/pipelines/github/deliverr/data-knex-snowflake-dialect?branch=0.x, I see: 
![image](https://github.com/user-attachments/assets/e877c7e6-b393-47ce-ad7c-6bf79015f799)

Is the notation difference related ?

2024-09-27 16:48 UTC, mbradydeliverr commented on .circleci/config.yml
> +              only: master,0.x
Yea, I got the notation wrong. It was the cause of the publish not running